const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const today=()=>new Date().toISOString().slice(0,10); const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,8);
let user='', state=null, timer=null, seconds=1500, timerMode='focus', audioCtx=null, noiseNode=null;
const usersKey='navo_users_v2'; const curKey='navo_current_v2';
const defaults=(name='Mohammed')=>({profile:{name,bio:'Personal Operating System',xp:0,streak:1,lastActive:today(),focusMinutes:25,breakMinutes:5,theme:'dark',motion:'full',dailyGoal:3},spaces:[{id:'uni',name:'University',color:'#35d7ff'},{id:'dev',name:'Coding',color:'#7c3aed'},{id:'life',name:'Personal',color:'#ffc078'},{id:'fivem',name:'FiveM',color:'#39d98a'}],tasks:[{id:uid(),title:'حدد أهم شيء اليوم',space:'Personal',priority:'High',date:today(),done:false,pinned:true},{id:uid(),title:'جلسة تركيز 25 دقيقة',space:'Coding',priority:'Medium',date:today(),done:false}],notes:{[today()]:''},activity:{},sessions:0});
const hash=async txt=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(txt)))).map(b=>b.toString(16).padStart(2,'0')).join('');
const getUsers=()=>JSON.parse(localStorage.getItem(usersKey)||'{}'); const setUsers=o=>localStorage.setItem(usersKey,JSON.stringify(o));
function dataKey(){return 'navo_state_'+user.toLowerCase()} function save(skip=false){localStorage.setItem(dataKey(),JSON.stringify(state)); if(!skip) render();}
function cleanName(n){return n.trim().replace(/\s+/g,'_').toLowerCase()} function esc(x){return String(x??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]))}
function toast(msg,type=''){const t=$('#toast'); t.textContent=msg; t.className='toast show '+type; clearTimeout(toast.t); toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function setAuthMode(m){const form=$('#authForm'); form.dataset.mode=m; $('#loginModeBtn').classList.toggle('active',m==='login'); $('#registerModeBtn').classList.toggle('active',m==='register'); $('#authTitle').textContent=m==='login'?'تسجيل الدخول':'إنشاء حساب'; $('#authEyebrow').textContent=m==='login'?'WELCOME BACK':'NEW ACCOUNT'; $('#authSubtitle').textContent=m==='login'?'ادخل باسم المستخدم وكلمة المرور.':'اختر يوزر نيم جديد وكلمة مرور قوية.'; $('#authSubmitBtn').textContent=m==='login'?'دخول':'إنشاء الحساب'; $('#authInlineMsg').textContent='';}
function load(name){user=name; const fresh=defaults(name); state=JSON.parse(localStorage.getItem(dataKey())||'null')||fresh; state.profile={...fresh.profile,...(state.profile||{})}; state.spaces=state.spaces?.length?state.spaces:fresh.spaces; state.tasks=state.tasks||[]; state.notes=state.notes||{}; state.activity=state.activity||{}; state.sessions=state.sessions||0; updateStreak(); seconds=(state.profile.focusMinutes||25)*60; applyPrefs(false);}
function updateStreak(){const last=state.profile.lastActive;if(last!==today()){const y=new Date(); y.setDate(y.getDate()-1); const ys=y.toISOString().slice(0,10); state.profile.streak=last===ys?(state.profile.streak||1)+1:1; state.profile.lastActive=today();}}
function showApp(){ $('#auth').classList.add('hidden'); $('#app').classList.remove('hidden'); $('#railUser').textContent='@'+user; render(); setTimeout(()=>$('#loader')?.classList.add('hide'),350)}
async function doLogin(e){e.preventDefault(); const raw=$('#userName').value; const pass=$('#userPass').value; const name=cleanName(raw); const msg=$('#authInlineMsg'); if(name.length<3||pass.length<6){msg.textContent='اليوزر 3 أحرف على الأقل وكلمة المرور 6 أحرف.';return} const mode=$('#authForm').dataset.mode; const users=getUsers(); const hp=await hash(name+':'+pass); if(mode==='register'){ if(users[name]){msg.textContent='اسم المستخدم موجود بالفعل. جرّب اسم ثاني.';return} users[name]={hash:hp,createdAt:new Date().toISOString()}; setUsers(users); localStorage.setItem(curKey,name); load(name); save(true); showApp(); toast('تم إنشاء الحساب بنجاح','ok'); return } if(!users[name]){msg.textContent='اسم المستخدم غير موجود. أنشئ حساب أولاً.';return} if(users[name].hash!==hp){msg.textContent='كلمة المرور غير صحيحة.';return} localStorage.setItem(curKey,name); load(name); showApp(); toast('تم تسجيل الدخول','ok')}
function logout(){localStorage.removeItem(curKey); stopTimer(); location.reload()}
function applyPrefs(toggleTheme){ if(toggleTheme) state.profile.theme=state.profile.theme==='light'?'dark':'light'; document.body.classList.toggle('light',state.profile.theme==='light'); document.body.classList.toggle('motion-off',state.profile.motion==='off'); document.body.classList.toggle('motion-soft',state.profile.motion==='soft'); $('#themeBtn') && ($('#themeBtn').textContent=state.profile.theme==='light'?'☀':'☾'); save(true)}
function page(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('.nav,.mnav').forEach(b=>b.classList.toggle('active',b.dataset.page===id)); const titles={center:'Command Center',today:'Today',focus:'Focus Room',spaces:'Spaces',dump:'Brain Dump',insights:'Insights',profile:'Profile',settings:'Settings'}; $('#pageTitle').textContent=titles[id]||'Navo'; if(id==='focus') updateTimer(false)}
function rank(){const x=state.profile.xp||0; return x>=2500?'Master':x>=1200?'Deep Worker':x>=500?'Builder':x>=120?'Starter':'Rookie'} function level(){return Math.floor((state.profile.xp||0)/200)+1} function tasksToday(){return state.tasks.filter(t=>(t.date||today())===today())} function doneToday(){return tasksToday().filter(t=>t.done).length} function bestTask(){return state.tasks.find(t=>!t.done&&t.pinned)||state.tasks.find(t=>!t.done&&t.priority==='High')||state.tasks.find(t=>!t.done)||null} function completion(){return Math.round((state.tasks.filter(t=>t.done).length/Math.max(1,state.tasks.length))*100)}
function taskHTML(t){return `<div class="task ${t.done?'done':''}" data-id="${t.id}"><div class="task-main"><button class="check doneBtn" data-id="${t.id}">${t.done?'✓':''}</button><div><h4>${t.pinned?'📌 ':''}${esc(t.title)}</h4><div class="meta"><span class="tag">${esc(t.space||'Personal')}</span><span class="tag">${esc(t.priority)}</span><span class="tag">${(t.date||today())===today()?'اليوم':esc(t.date||'')}</span></div></div></div><div class="task-actions"><button class="mini pinBtn" data-id="${t.id}">📌</button><button class="mini delBtn" data-id="${t.id}">×</button></div></div>`}
function empty(t){return `<div class="task"><div><h4>${esc(t)}</h4><div class="meta"><span class="tag">Navo</span></div></div></div>`}
function filtered(){const q=($('#taskSearch')?.value||'').toLowerCase(); const f=$('#taskFilter')?.value||'all'; let arr=tasksToday().filter(t=>(t.title+' '+t.space).toLowerCase().includes(q)); if(f==='open')arr=arr.filter(t=>!t.done); if(f==='done')arr=arr.filter(t=>t.done); if(f==='high')arr=arr.filter(t=>t.priority==='High'); return arr}
function insight(){const open=state.tasks.filter(t=>!t.done).length, high=state.tasks.filter(t=>!t.done&&t.priority==='High').length; if(high>1)return `عندك ${high} مهام عالية. ابدأ بواحدة فقط وخلي الباقي بعدين.`; if(open===0)return 'اليوم نظيف. تقدر تضيف هدف خفيف أو تأخذ راحة.'; if((state.sessions||0)===0)return 'جلسة 25 دقيقة الآن بتعطيك بداية قوية.'; return 'أداؤك يتحسن مع الجلسات القصيرة. كمل بنفس الهدوء.'}
function render(){ if(!state)return; $('#dateText').textContent=new Date().toLocaleDateString('ar-SA',{weekday:'long',month:'long',day:'numeric'}); const best=bestTask(), pct=Math.round(doneToday()/Math.max(1,state.profile.dailyGoal||3)*100); $('#mainGreeting').textContent=`هلا ${state.profile.name}، خلك على أهم شيء.`; $('#aiInsight').textContent=insight(); $('#todayPct').textContent=Math.min(100,pct)+'%'; $('#ringFill').style.width=Math.min(100,pct)+'%'; $('#oneThing').textContent=best?best.title:'كل شيء منجز'; $('#oneThingMeta').textContent=best?`${best.space} • ${best.priority}`:'خذ راحة أو أضف هدف جديد'; $('#streak').textContent=state.profile.streak; $('#xp').textContent=state.profile.xp; $('#rank').textContent=rank(); $('#sessions').textContent=state.sessions; $('#nextTasks').innerHTML=state.tasks.filter(t=>!t.done).slice(0,4).map(taskHTML).join('')||empty('كل المهام منجزة'); $('#taskList').innerHTML=filtered().map(taskHTML).join('')||empty('ما فيه مهام اليوم'); $('#dailyNote').value=state.notes[today()]||''; $('#focusTask').textContent=best?best.title:'جلسة تركيز هادئة'; $('#taskSpace').innerHTML=state.spaces.map(s=>`<option>${esc(s.name)}</option>`).join(''); renderSpaces(); renderInsights(); renderProfile(); renderSettings(); bindTasks(); updateTimer(false); }
function bindTasks(){ $$('.doneBtn').forEach(b=>b.onclick=()=>toggleTask(b.dataset.id)); $$('.delBtn').forEach(b=>b.onclick=()=>delTask(b.dataset.id)); $$('.pinBtn').forEach(b=>b.onclick=()=>pinTask(b.dataset.id)); }
function markActivity(n=1){state.activity[today()]=(state.activity[today()]||0)+n} function addTask(title,space='Personal',priority='Medium',date=today()){state.tasks.unshift({id:uid(),title,space,priority,date,done:false,pinned:false}); markActivity(1); save();}
function toggleTask(id){const t=state.tasks.find(x=>x.id===id); if(!t)return; t.done=!t.done; if(t.done){t.doneAt=new Date().toISOString(); state.profile.xp += t.priority==='High'?70:t.priority==='Medium'?45:25; markActivity(2); toast('إنجاز جديد +XP','ok')}else{t.doneAt=''} save()}
function delTask(id){state.tasks=state.tasks.filter(t=>t.id!==id); save(); toast('تم حذف المهمة')} function pinTask(id){state.tasks.forEach(t=>t.pinned=false); const t=state.tasks.find(t=>t.id===id); if(t)t.pinned=true; save(); toast('تم تثبيت المهمة','ok')}
function renderSpaces(){const counts={}; state.tasks.forEach(t=>counts[t.space]=(counts[t.space]||0)+1); $('#spacesGrid').innerHTML=state.spaces.map(s=>`<article class="space glass" style="--space:${s.color}"><span class="eyebrow">SPACE</span><h3>${esc(s.name)}</h3><p>${counts[s.name]||0} مهام • مساحة خاصة للتركيز</p><div class="space-actions"><button class="ghost addInSpace" data-space="${esc(s.name)}">＋ مهمة</button><button class="ghost openSpace" data-space="${esc(s.name)}">عرض</button></div></article>`).join(''); $$('.addInSpace').forEach(b=>b.onclick=()=>openTaskDialog(b.dataset.space)); $$('.openSpace').forEach(b=>b.onclick=()=>{page('today'); $('#taskSearch').value=b.dataset.space; render()})}
function renderInsights(){const rate=completion(); $('#completionRate').textContent=rate+'%'; const counts={}; state.tasks.forEach(t=>counts[t.space]=(counts[t.space]||0)+1); $('#bestSpace').textContent=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'—'; $('#weeklyText').textContent=rate>60?'أداؤك ممتاز. حافظ على نفس الرتم.':'ابدأ بجلسات قصيرة ومهام قليلة عشان تبني رتم ثابت.'; let html=''; for(let i=27;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i); const k=d.toISOString().slice(0,10); const v=state.activity[k]||0; html+=`<i class="heat ${v>4?'l3':v>2?'l2':v>0?'l1':''}" title="${k}: ${v}"></i>`} $('#heatmap').innerHTML=html}
function renderProfile(){const l=level(); $('#profileName').textContent=state.profile.name; $('#profileBio').textContent=state.profile.bio; $('#avatar').textContent=(state.profile.name||user||'N')[0].toUpperCase(); $('#levelLabel').textContent='Level '+l+' • '+rank(); $('#levelFill').style.width=((state.profile.xp%200)/2)+'%'; $('#profileXpMini').textContent=state.profile.xp; $('#profileFocusMini').textContent=state.sessions; $('#profileSpacesMini').textContent=state.spaces.length; $('#profileTasksMini').textContent=state.tasks.length;}
function renderSettings(){ $('#displayName').value=state.profile.name; $('#bioInput').value=state.profile.bio; $('#focusMinutes').value=state.profile.focusMinutes; $('#breakMinutes').value=state.profile.breakMinutes; $('#motionSelect').value=state.profile.motion||'full'; $('#focusLengthLabel').textContent=state.profile.focusMinutes+'m'; $('#breakLengthLabel').textContent=state.profile.breakMinutes+'m'; $('#focusSessionLabel').textContent=state.sessions; $('#nightScore').textContent=state.profile.theme==='light'?'Light':'Calm';}
function openTaskDialog(space){$('#taskTitle').value=''; $('#taskDate').value=today(); if(space) $('#taskSpace').value=space; $('#taskDialog').showModal()}
function sortTasks(){const order={High:0,Medium:1,Low:2}; state.tasks.sort((a,b)=>(a.done-b.done)||(b.pinned-a.pinned)||(order[a.priority]-order[b.priority])||String(a.date).localeCompare(String(b.date))); save(); toast('ترتيب ذكي جاهز','ok')}
function stopTimer(){clearInterval(timer); timer=null; $('#focusRoom')?.classList.remove('running')} function updateTimer(){const m=String(Math.floor(seconds/60)).padStart(2,'0'), s=String(seconds%60).padStart(2,'0'); $('#timer').textContent=`${m}:${s}`; const total=(timerMode==='focus'?state.profile.focusMinutes:state.profile.breakMinutes)*60; const off=704-(704*(total-seconds)/Math.max(1,total)); $('#timerCircle').style.strokeDashoffset=off; $('#timerLabel').textContent=timerMode==='focus'?'جلسة تركيز':'راحة قصيرة'}
function startTimer(){if(timer)return; $('#focusRoom').classList.add('running'); timer=setInterval(()=>{seconds--; updateTimer(); if(seconds<=0){stopTimer(); if(timerMode==='focus'){state.sessions++; state.profile.xp+=100; markActivity(3); timerMode='break'; seconds=state.profile.breakMinutes*60; toast('خلصت جلسة التركيز +100XP','ok')}else{timerMode='focus'; seconds=state.profile.focusMinutes*60; toast('انتهت الراحة')} save(); updateTimer();}},1000)} function resetTimer(){stopTimer(); timerMode='focus'; seconds=state.profile.focusMinutes*60; updateTimer()} function pauseTimer(){stopTimer(); toast('تم إيقاف المؤقت')}
function setSound(type){$$('.sound').forEach(b=>b.classList.toggle('active',b.dataset.sound===type)); if(noiseNode){noiseNode.stop?.(); noiseNode.disconnect?.(); noiseNode=null} if(type==='none')return; audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)(); const osc=audioCtx.createOscillator(), gain=audioCtx.createGain(); osc.frequency.value=type==='rain'?180:type==='cafe'?95:55; gain.gain.value=.025; osc.type=type==='space'?'sine':'triangle'; osc.connect(gain).connect(audioCtx.destination); osc.start(); noiseNode=osc;}
function command(open=true){$('#cmd').classList.toggle('hidden',!open); if(open){$('#cmdInput').value=''; $('#cmdInput').focus(); $('#cmdList').innerHTML=['Focus Room','مهمة جديدة','Brain Dump','Settings'].map(x=>`<div class="cmd-item">${x}</div>`).join(''); $$('.cmd-item').forEach((el,i)=>el.onclick=()=>{command(false); if(i===0)page('focus'); if(i===1)openTaskDialog(); if(i===2)page('dump'); if(i===3)page('settings')})}}
window.addEventListener('load',()=>{let p=0; const bar=$('#loaderBar'); const int=setInterval(()=>{p+=18; if(bar)bar.style.width=Math.min(100,p)+'%'; if(p>=100)clearInterval(int)},180); setTimeout(()=>$('#loader')?.classList.add('hide'),950); if('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(()=>{}); const last=localStorage.getItem(curKey); if(last){load(last);showApp();}});
$('#loginModeBtn').onclick=()=>setAuthMode('login'); $('#registerModeBtn').onclick=()=>setAuthMode('register'); $('#authForm').onsubmit=doLogin; $('#demoBtn').onclick=async()=>{const users=getUsers(); if(!users.demo)users.demo={hash:await hash('demo:123456'),createdAt:new Date().toISOString()}; setUsers(users); localStorage.setItem(curKey,'demo'); load('demo'); showApp();};
$('#logout').onclick=logout; $('#logoutSettings').onclick=logout; $('#cloudDisconnect').onclick=()=>{localStorage.removeItem(curKey); toast('تم مسح جلسة الدخول')}; $('#cloudSyncNow').onclick=()=>{save(true); toast('تم حفظ نسخة محلية','ok')};
$('#themeBtn').onclick=()=>applyPrefs(true); $('#themeMirrorBtn').onclick=()=>applyPrefs(true); $('#motionSelect').onchange=e=>{state.profile.motion=e.target.value; applyPrefs(false); toast('تم تحديث الحركة','ok')};
$$('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page)); document.addEventListener('click',e=>{const b=e.target.closest('[data-jump]'); if(b) page(b.dataset.jump)}); $('#quickAdd').onclick=()=>openTaskDialog(); $('#addTaskToday').onclick=()=>openTaskDialog(); $('#closeTask').onclick=()=>$('#taskDialog').close(); $('#taskForm').onsubmit=e=>{e.preventDefault(); addTask($('#taskTitle').value.trim(),$('#taskSpace').value,$('#taskPriority').value,$('#taskDate').value||today()); $('#taskDialog').close(); toast('تمت إضافة المهمة','ok')};
$('#taskSearch').oninput=render; $('#taskFilter').onchange=render; $('#sortTasks').onclick=sortTasks; $('#dailyNote').oninput=e=>{state.notes[today()]=e.target.value; save(true)}; $('#addSpace').onclick=()=>{const name=prompt('اسم المساحة الجديدة؟'); if(!name)return; const colors=['#35d7ff','#7c3aed','#ffc078','#39d98a','#ff5f7a']; state.spaces.push({id:uid(),name,color:colors[state.spaces.length%colors.length]}); save(); toast('تمت إضافة Space','ok')};
$('#parseDump').onclick=()=>{const text=$('#dumpInput').value.trim(); if(!text)return toast('اكتب أفكارك أول'); const parts=text.split(/\n|،|,| و | - /).map(x=>x.trim()).filter(x=>x.length>2).slice(0,8); $('#dumpResult').innerHTML=parts.map((p,i)=>`<div class="task"><div><h4>${esc(p)}</h4><div class="meta"><span class="tag">${i===0?'High':'Medium'}</span><span class="tag">Brain Dump</span></div></div><button class="primary addParsed" data-title="${esc(p)}" data-priority="${i===0?'High':'Medium'}">إضافة</button></div>`).join('')||empty('ما قدرت أستخرج مهام واضحة'); $$('.addParsed').forEach(b=>b.onclick=()=>{addTask(b.dataset.title,'Personal',b.dataset.priority,today()); b.textContent='تم'; b.disabled=true})};
$('#saveProfile').onclick=()=>{state.profile.name=$('#displayName').value.trim()||state.profile.name; state.profile.bio=$('#bioInput').value.trim()||'Personal Operating System'; state.profile.focusMinutes=Math.min(90,Math.max(5,+$('#focusMinutes').value||25)); state.profile.breakMinutes=Math.min(30,Math.max(1,+$('#breakMinutes').value||5)); resetTimer(); save(); toast('تم حفظ الإعدادات','ok')}; $('#focusMinutes').onchange=$('#breakMinutes').onchange=()=>$('#saveProfile').click();
$('#startFocusHero').onclick=()=>{page('focus'); startTimer()}; $('#startTimer').onclick=startTimer; $('#pauseTimer').onclick=pauseTimer; $('#resetTimer').onclick=resetTimer; $('#fullBtn').onclick=()=>$('#focusRoom').requestFullscreen?.(); $$('.sound').forEach(b=>b.onclick=()=>setSound(b.dataset.sound)); $('#openCmd').onclick=()=>command(true); $('#cmd').onclick=e=>{if(e.target.id==='cmd')command(false)}; document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();command(true)} if(e.key==='Escape')command(false)});
